trigger:
- master

pool:
  vmImage: 'macOS-latest'  # Use 'macOS-latest' for iOS builds or 'ubuntu-latest' for Android builds

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

# Build the project
- script: |
    npm run build
  displayName: 'Build the project'

# Run tests
- script: |
    npm test
  displayName: 'Run tests'

# For Android, you might want to build the APK
# - script: |
#     cd android
#     ./gradlew assembleRelease
#   displayName: 'Build Android APK'

- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
