trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Atualize para a versão 20.x do Node.js
  displayName: 'Install Node.js'

- script: npm install -g expo-cli
  displayName: 'Install Expo CLI'

- script: npm install
  displayName: 'Install dependencies'

- script: npm install --save-dev @expo/webpack-config --legacy-peer-deps
  displayName: 'Install Webpack for Expo'

- script: npm run build
  displayName: 'Build Expo project'
